### ISSUE TITLE
Why not use the SBApplication pid?

### ISSUE THREAD

**Issue by kylehowells** [b3ll/MessageBox-olde#10]
Here's the PID (proccess id) is gotten by using a clever little function `PIDForProcessNamed(@"Facebook")`:
https://github.com/b3ll/MessageBox/blob/master/MessageBox/ABMessageBox.mm#L168

However a line or 2 further down this happens: `SBApplication *fb =...` SBApplication has a pid property.
Why not just do `[fb pid]` and save trouble?

(not really an 'issue' but rather a genuine technical question)

**Comment by b3ll** [comment]
Oh. Yeah that wasn't working before, now it seems to be fine... funny how that works :P 

I'll change that though, thanks!
