### ISSUE TITLE
Message Box causes Facebook to crash

### ISSUE THREAD

**Issue by Mikey625** [b3ll/MessageBox-olde#12]
As of the new Facebook update 13 May 2013 Message Box just causes Facebook to crah after a few minutes.

**Comment by alexejk** [comment]
In my case (as of todays facebook update), when closing down Facebook (pressing Home) it stays on top of other windows (and only hides TabBar at the bottom).

This could be that chat heads has been changed in FB app.

**Comment by laverdet** [comment]
Also experiencing this. Had to uninstall MessageBox in order to use Facebook.

**Comment by laverdet** [comment]
We love you.

**Comment by b3ll** [comment]
haha thanks!
