### ISSUE TITLE
Locking results in stuck keyboard

### ISSUE THREAD

**Issue by JPNYC81** [b3ll/MessageBox-olde#13]
When locking the device, if the keyboard is up from MessageBox then the keyboard will stay up, over any other on screen elements (making it impossible to unlock the phone from the lock screen). 

Awesome tweak btw, thanks ;)
-JP

![photo](https://f.cloud.github.com/assets/5191352/932750/aa57e10a-0046-11e3-9d9b-db26dbe32cd6.PNG)

**Comment by b3ll** [comment]
Fixed in upcoming update
