### ISSUE TITLE
Message Box iOS 7 Support

### ISSUE THREAD

**Issue by KnightYoshi** [b3ll/MessageBox-olde#14]
So will you be working on this to support iOS 7 (both 32 & 64-bit)?

**Comment by joelitonsilva** [comment]
Por favor atualize o message box pra ios 7!! E se possível inclua as mensagens do whatsapp..

**Comment by joelitonsilva** [comment]
Please update the message box for ios 7! And if possible include messages from whatsapp ..

**Comment by A-Cardwell91** [comment]
Update for iOS 7 would be awesome!! Though I would prefer the chat heads in the Facebook paper app more then the Facebook main or messenger app!!
