### ISSUE TITLE
Tweak Does Nothing

### ISSUE THREAD

**Issue by dotAlexX** [b3ll/MessageBox-olde#3]
iPhone 4S

I'm running:
Adblocker
Auxo
CallBar
Copic
FBPrivacy
Front HDR
Haptic Pro
Navigate From Maps
Nitrous
Springtomize

I think Springtomize may be causing the issue and making chat heads not appear in Springboard.

**Comment by kylehowells** [comment]
Step 1: check you are on iOS 6; step 2: open facebook app; Step 3: open a message from someone; Step 4: leave the chat head on screen; Step 5: close app; Step 6: chat head should now show on the home screen.
Does doing this do anything.
