### ISSUE TITLE
Message Box not working at all

### ISSUE THREAD

**Issue by Segarac** [b3ll/MessageBox-olde#9]
Howdy. Today I installed Message Box 1.0-8 on iOS 6.0.2 on the iPhone 5 and afterward it made my facebook app crash, and the chat heads were nowhere to be found. It appears that the the package didn't work at all, and I'm not sure if it's just my iPhone or if it's the code.

I'd really like to try this out, so I'd appreciate if you could look into it or give me some feedback on what I can do to make it work.

Let me know if you need any additional info too.

Thanks,
Segarac

**Comment by Malvix** [comment]
That version of Message Box is only compatible with earlier versions of facebook. I believe the latest version supported is 6.0.2
